apiVersion: v1
kind: Service
metadata:
  name: cv-one-page-service
  namespace: cv-one-page
spec:
  type: NodePort
  selector:
    app: cv-one-page
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30085   # NodePort expos√©
